/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zjucvg_rtreconstruction_OpenCLUtility */

#ifndef _Included_net_zjucvg_rtreconstruction_OpenCLUtility
#define _Included_net_zjucvg_rtreconstruction_OpenCLUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zjucvg_rtreconstruction_OpenCLUtility
 * Method:    gray2Bitmap
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_zjucvg_rtreconstruction_OpenCLUtility_gray2Bitmap
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
