/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zjucvg_rtreconstruction_NativeVSLAM_IMU */

#ifndef _Included_net_zjucvg_rtreconstruction_NativeVSLAM_IMU
#define _Included_net_zjucvg_rtreconstruction_NativeVSLAM_IMU
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
